demo: 
  helixClusterName: "${HELIX_CLUSTER_NAME:rabbitmq consumer cluster}"
  partitionCount: "${PARTITIONS_COUNT:3}"
  resourceName: "${RESOURCE_NAME:topic}"
  stateModel: OnlineOffline
  zookeeperAddress: "${ZK_ADDRESS:localhost:2181}"
