demo:
      stateModel: OnlineOffline
      zookeeperAddress: ${ZK_ADDRESS:zk:2181}
      helixClusterName: ${HELIX_CLUSTER_NAME:rcx-events-publisher}
      partitionCount: ${PARTITIONS_COUNT:3}
      resourceName: ${RESOURCE_NAME:oplog.rs}
      